/* ---------------------------------------------------------------
   OneGoodThought — curated content (R5, R11, R14)

   APPEND-ONLY. Kept links (R9) encode positions in `affirmations`,
   so reordering or removing an entry silently changes what someone's
   saved link shows. New affirmations go at the end, always.

   f: feelings it suits    anxious | low | overwhelmed | tired | angry | steady
   c: situations it suits  work | people | health | money | change | self | none

   hy = Eastern Armenian. Machine-drafted; the affirmations carry the
   whole product's tone and should be reviewed by a native speaker.
   --------------------------------------------------------------- */

window.OGT_CONTENT = {

  languages: [
    { id: 'en', label: 'EN', name: 'English' },
    { id: 'hy', label: 'ՀԱՅ', name: 'Հայերեն' }
  ],

  ui: {
    en: {
      title: 'One good thought is enough.',
      q1: 'How are you feeling?',
      q2: 'What is affecting you?',
      step: 'Step {n} of 2',
      back: 'Back',
      another: 'Another',
      keep: 'Keep',
      kept: 'Kept',
      remove: 'Remove',
      copyLink: 'Copy link',
      copied: 'Link copied',
      copyFail: 'Copy from the address bar',
      fiveGood: 'Five good things',
      keptThoughts: 'Kept thoughts',
      howIveBeen: "How I've been",
      howYouveBeen: "How you've been",
      today: 'Today',
      home: 'Today',
      clear: 'Clear history',
      clearArm: 'Tap again to clear',
      change: 'change',
      changeLabel: 'Change how you are feeling today',
      saved: 'Saved',
      notSaved: 'Not saved — this browser blocks storage',
      gratitudeIntro: "Today's prompts. Answer what you can — blanks are fine.",
      linkNote: 'Your kept thoughts live in this link. Save it to keep them.',
      storageBlocked: 'This browser is blocking storage, so check-ins from this visit will not be saved.',
      colDate: 'Date',
      colFelt: 'Felt',
      colAbout: 'About',
      fallback: "You're doing okay. That's enough for today.",
      themeToLight: 'Switch to light mode',
      themeToDark: 'Switch to dark mode',
      langLabel: 'Language',
      prevKept: 'Previous kept thought',
      nextKept: 'Next kept thought',
      anotherLabel: 'Show another thought',
      keepLabel: 'Keep this thought',
      keptLabel: 'Kept. Select to remove from your kept thoughts',
      removeLabel: 'Remove this thought from your kept thoughts'
    },
    hy: {
      title: 'Մեկ լավ միտքը բավական է։',
      q1: 'Ինչպե՞ս ես քեզ զգում։',
      q2: 'Ի՞նչն է քեզ ազդում։',
      step: 'Քայլ {n} / 2',
      back: 'Հետ',
      another: 'Մեկ ուրիշ',
      keep: 'Պահել',
      kept: 'Պահված',
      remove: 'Հեռացնել',
      copyLink: 'Պատճենել հղումը',
      copied: 'Հղումը պատճենվեց',
      copyFail: 'Պատճենիր հասցեագոտուց',
      fiveGood: 'Հինգ լավ բան',
      keptThoughts: 'Պահված մտքեր',
      howIveBeen: 'Ինչպես եմ եղել',
      howYouveBeen: 'Ինչպես ես եղել',
      today: 'Այսօր',
      home: 'Այսօր',
      clear: 'Մաքրել պատմությունը',
      clearArm: 'Կրկին սեղմիր մաքրելու համար',
      change: 'փոխել',
      changeLabel: 'Փոխիր, թե ինչպես ես քեզ զգում այսօր',
      saved: 'Պահպանված է',
      notSaved: 'Չպահպանվեց — զննարկիչն արգելափակում է պահոցը',
      gratitudeIntro: 'Այսօրվա հարցերը։ Պատասխանիր այնքան, որքան կարող ես — դատարկը նորմալ է։',
      linkNote: 'Քո պահված մտքերն ապրում են այս հղումում։ Պահպանիր այն։',
      storageBlocked: 'Այս զննարկիչն արգելափակում է պահոցը, ուստի այս այցի գրառումները չեն պահվի։',
      colDate: 'Ամսաթիվ',
      colFelt: 'Զգացումը',
      colAbout: 'Ինչի մասին',
      fallback: 'Դու լավ ես անում։ Այսօրվա համար դա բավական է։',
      themeToLight: 'Անցնել լուսավոր տեսքի',
      themeToDark: 'Անցնել մուգ տեսքի',
      langLabel: 'Լեզու',
      prevKept: 'Նախորդ պահված միտքը',
      nextKept: 'Հաջորդ պահված միտքը',
      anotherLabel: 'Ցույց տալ մեկ ուրիշ միտք',
      keepLabel: 'Պահել այս միտքը',
      keptLabel: 'Պահված է։ Ընտրիր՝ հեռացնելու համար',
      removeLabel: 'Հեռացնել այս միտքը պահվածներից'
    }
  },

  feelings: [
    { id: 'anxious',     en: 'Anxious',     hy: 'Անհանգիստ' },
    { id: 'low',         en: 'Low',         hy: 'Ընկճված' },
    { id: 'overwhelmed', en: 'Overwhelmed', hy: 'Ծանրաբեռնված' },
    { id: 'tired',       en: 'Tired',       hy: 'Հոգնած' },
    { id: 'angry',       en: 'Frustrated',  hy: 'Վրդովված' },
    { id: 'steady',      en: 'Steady',      hy: 'Հանգիստ' }
  ],

  contexts: [
    { id: 'work',   en: 'Work',             hy: 'Աշխատանք' },
    { id: 'people', en: 'People',           hy: 'Մարդիկ' },
    { id: 'health', en: 'My body',          hy: 'Իմ մարմինը' },
    { id: 'money',  en: 'Money',            hy: 'Փող' },
    { id: 'change', en: 'Uncertainty',      hy: 'Անորոշություն' },
    { id: 'self',   en: 'Myself',           hy: 'Ինքս ինձ' },
    { id: 'none',   en: 'Nothing specific', hy: 'Ոչ մի կոնկրետ բան' }
  ],

  prompts: [
    { en: 'Someone who made this week easier',            hy: 'Մեկը, ով այս շաբաթն ավելի հեշտ դարձրեց' },
    { en: 'Something your body did for you today',        hy: 'Մի բան, որ քո մարմինն արեց քեզ համար այսօր' },
    { en: 'A small thing that went right',                hy: 'Մի փոքր բան, որ լավ ստացվեց' },
    { en: "Something you're glad you didn't put off",     hy: 'Մի բան, որ ուրախ ես, որ չհետաձգեցիր' },
    { en: 'A place you felt comfortable in',              hy: 'Մի տեղ, որտեղ հարմարավետ էիր զգում' },
    { en: 'Something someone said that stayed with you',  hy: 'Մի բան, որ մեկն ասաց և մնաց քեզ հետ' },
    { en: 'Something you own that still works',           hy: 'Մի բան, որ ունես և դեռ աշխատում է' },
    { en: 'Something you learned recently, however small', hy: 'Մի բան, որ վերջերս սովորեցիր, թեկուզ փոքր' },
    { en: 'A meal you actually enjoyed',                  hy: 'Ուտելիք, որն իսկապես վայելեցիր' },
    { en: 'Something you handle better than you used to', hy: 'Մի բան, որ ավելի լավ ես հաղթահարում, քան առաջ' },
    { en: 'A sound you were glad to hear',                hy: 'Ձայն, որը ուրախ էիր լսել' },
    { en: 'Someone who is easy to be around',             hy: 'Մեկը, ում կողքին հեշտ է լինել' },
    { en: 'Something you were trusted with',              hy: 'Մի բան, որ քեզ վստահեցին' },
    { en: "A moment today that wasn't difficult",         hy: 'Մի պահ այսօր, որը դժվար չէր' },
    { en: "Something you're looking forward to",          hy: 'Մի բան, որին անհամբեր սպասում ես' }
  ],

  affirmations: [
    { en: "You don't have to have it figured out today.", hy: 'Պարտադիր չէ, որ այսօր ամեն ինչ պարզ լինի։', f: ['anxious','overwhelmed'], c: ['change','work','self'] },
    { en: 'Rest is not something you have to earn.', hy: 'Հանգիստը վաստակելու բան չէ։', f: ['tired','overwhelmed'], c: ['work','self','health'] },
    { en: 'You are allowed to move slower than you think you should.', hy: 'Դու իրավունք ունես ավելի դանդաղ շարժվել, քան կարծում ես՝ պետք է։', f: ['overwhelmed','tired'], c: ['work','self','health'] },
    { en: 'One honest step counts more than ten perfect ones.', hy: 'Մեկ անկեղծ քայլն ավելի արժե, քան տասը կատարյալը։', f: ['overwhelmed','anxious'], c: ['work','self'] },
    { en: 'You can be proud of yourself and still have work to do.', hy: 'Կարող ես հպարտ լինել քեզնով և դեռ անելիք ունենալ։', f: ['low','steady'], c: ['work','self'] },
    { en: 'Nothing is wrong with you for needing a break.', hy: 'Ոչինչ սխալ չէ քո մեջ, եթե դադարի կարիք ունես։', f: ['tired','overwhelmed'], c: ['work','health','self'] },
    { en: "You've survived every hard day so far. That's not nothing.", hy: 'Մինչ այժմ դիմացել ես ամեն ծանր օրվա։ Դա քիչ բան չէ։', f: ['low','anxious'], c: ['change','health','none'] },
    { en: "It's okay to want things to be easier.", hy: 'Նորմալ է ուզել, որ ամեն ինչ ավելի հեշտ լինի։', f: ['tired','low','overwhelmed'], c: ['money','work','health'] },
    { en: "You don't owe anyone constant progress.", hy: 'Դու ոչ ոքի պարտք չես մշտական առաջընթաց։', f: ['tired','low'], c: ['work','self','people'] },
    { en: 'Today can be small and still be enough.', hy: 'Այսօրը կարող է փոքր լինել և միևնույն է՝ բավական։', f: ['tired','low','overwhelmed'], c: ['none','self'] },
    { en: "You're allowed to change your mind.", hy: 'Դու իրավունք ունես փոխել քո միտքը։', f: ['anxious','steady'], c: ['change','work','people'] },
    { en: "Being tired isn't a character flaw.", hy: 'Հոգնած լինելը բնավորության թերություն չէ։', f: ['tired'], c: ['health','work','self'] },
    { en: 'You can start again without explaining why you stopped.', hy: 'Կարող ես նորից սկսել՝ առանց բացատրելու, թե ինչու ես կանգ առել։', f: ['low','steady'], c: ['change','self','work'] },
    { en: 'Not every day has to feel like growth to count.', hy: 'Պարտադիր չէ ամեն օր աճ զգալ, որ այն հաշվի առնվի։', f: ['low','tired'], c: ['self','none'] },
    { en: "You're doing better than the voice in your head says.", hy: 'Դու ավելի լավ ես անում, քան ասում է ձայնը քո գլխում։', f: ['low','anxious'], c: ['self'] },
    { en: "It's fine to need reminding of things you already know.", hy: 'Նորմալ է, որ պետք է հիշեցնել քեզ արդեն իմացած բաները։', f: ['low','anxious'], c: ['self','none'] },
    { en: 'You can care about this and still take it slow.', hy: 'Կարող ես հոգ տանել այս մասին և միևնույն է՝ դանդաղ առաջ գնալ։', f: ['overwhelmed','anxious'], c: ['work','people','health'] },
    { en: 'Some days, showing up is the whole job.', hy: 'Որոշ օրեր ներկա լինելը ողջ գործն է։', f: ['tired','overwhelmed'], c: ['work','none'] },
    { en: "You're not behind. There was never a schedule.", hy: 'Դու հետ չես մնացել։ Ժամանակացույց երբեք չի եղել։', f: ['anxious','low'], c: ['change','self','work'] },
    { en: "You can hold two things: this is hard, and you're okay.", hy: 'Կարող ես երկուսն էլ պահել՝ սա դժվար է, և դու լավ ես։', f: ['anxious','low','angry'], c: ['none','change','health'] },
    { en: 'Whatever you did today was done by someone trying.', hy: 'Ինչ էլ արել ես այսօր, արել է մեկը, ով փորձում է։', f: ['low','tired'], c: ['self','work'] },
    { en: "You don't need permission to rest, but here it is anyway.", hy: 'Հանգստանալու համար թույլտվություն պետք չէ, բայց ահա այն։', f: ['tired','overwhelmed'], c: ['work','health'] },
    { en: "You're allowed to take up space without a reason.", hy: 'Դու իրավունք ունես տեղ զբաղեցնել՝ առանց պատճառի։', f: ['low','anxious'], c: ['people','self'] },
    { en: "This moment doesn't need to be productive to matter.", hy: 'Այս պահը պարտադիր չէ արդյունավետ լինի, որ կարևոր լինի։', f: ['tired','overwhelmed','steady'], c: ['work','none','self'] },
    { en: 'Your anger is information, not a failure of character.', hy: 'Քո զայրույթը տեղեկություն է, ոչ թե բնավորության թերություն։', f: ['angry'], c: ['self','people','work'] },
    { en: 'You can be furious and still be fair to yourself.', hy: 'Կարող ես կատաղած լինել և միևնույն է՝ արդար քեզ հանդեպ։', f: ['angry'], c: ['self','people'] },
    { en: 'Not every unfair thing needs your energy today.', hy: 'Ամեն անարդար բան այսօր քո ուժի կարիքը չունի։', f: ['angry','tired'], c: ['work','people'] },
    { en: "You're allowed to be upset about something that hurt.", hy: 'Դու իրավունք ունես վրդովվել մի բանից, որը ցավ պատճառեց։', f: ['angry','low'], c: ['people','self'] },
    { en: "Frustration usually means you cared. That isn't a flaw.", hy: 'Հիասթափությունը սովորաբար նշանակում է՝ քեզ համար կարևոր էր։ Դա թերություն չէ։', f: ['angry'], c: ['work','people','self'] },
    { en: "Being careful with money isn't the same as failing at it.", hy: 'Փողի հարցում զգույշ լինելը ձախողում չէ։', f: ['anxious','low'], c: ['money'] },
    { en: 'Your worth was never a number in an account.', hy: 'Քո արժեքը երբեք հաշվի վրա եղած թիվ չի եղել։', f: ['low','anxious'], c: ['money','self'] },
    { en: 'Tight months are seasons, not verdicts.', hy: 'Դժվար ամիսները եղանակներ են, ոչ թե դատավճիռ։', f: ['anxious','low'], c: ['money','change'] },
    { en: 'You can want more without being ungrateful.', hy: 'Կարող ես ավելին ուզել՝ առանց ապերախտ լինելու։', f: ['low','steady'], c: ['money','work'] },
    { en: 'You can love someone and still need distance from them.', hy: 'Կարող ես սիրել մեկին և միևնույն է՝ հեռավորության կարիք ունենալ։', f: ['overwhelmed','angry'], c: ['people'] },
    { en: "Being hard to reach today doesn't make you a bad friend.", hy: 'Այսօր դժվար հասանելի լինելը քեզ վատ ընկեր չի դարձնում։', f: ['tired','overwhelmed'], c: ['people'] },
    { en: "Not everyone's reaction to you is a fact about you.", hy: 'Քեզ հանդեպ ամեն արձագանք փաստ չէ քո մասին։', f: ['anxious','low'], c: ['people','self'] },
    { en: 'You can disappoint someone and still be a good person.', hy: 'Կարող ես հիասթափեցնել մեկին և միևնույն է՝ լավ մարդ լինել։', f: ['anxious','overwhelmed'], c: ['people','self'] },
    { en: 'One awkward conversation is not the whole friendship.', hy: 'Մեկ անհարմար խոսակցությունը ողջ ընկերությունը չէ։', f: ['anxious'], c: ['people'] },
    { en: 'Your body is asking for something, not complaining.', hy: 'Քո մարմինը մի բան է խնդրում, ոչ թե բողոքում։', f: ['tired'], c: ['health'] },
    { en: "Healing rarely moves in a straight line. That's normal.", hy: 'Ապաքինումը հազվադեպ է ուղիղ գծով գնում։ Դա նորմալ է։', f: ['low','tired'], c: ['health','change'] },
    { en: 'You can take this at the pace your body sets.', hy: 'Կարող ես առաջ գնալ այն տեմպով, որ քո մարմինն է թելադրում։', f: ['tired','overwhelmed'], c: ['health'] },
    { en: 'A hard body day is not a personal failure.', hy: 'Մարմնի ծանր օրը անձնական ձախողում չէ։', f: ['low','angry'], c: ['health','self'] },
    { en: 'Not knowing yet is a normal part of finding out.', hy: 'Դեռ չիմանալը իմանալու ճանապարհի նորմալ մասն է։', f: ['anxious'], c: ['change','work'] },
    { en: 'You can be scared of a change you also chose.', hy: 'Կարող ես վախենալ փոփոխությունից, որն ինքդ ես ընտրել։', f: ['anxious'], c: ['change'] },
    { en: "Uncertainty is uncomfortable. It isn't dangerous.", hy: 'Անորոշությունն անհարմար է։ Վտանգավոր չէ։', f: ['anxious'], c: ['change'] },
    { en: "You've adapted to things you once thought impossible.", hy: 'Դու հարմարվել ես բաների, որ ժամանակին անհնար էիր համարում։', f: ['anxious','low'], c: ['change'] },
    { en: 'The job is not the whole measure of you.', hy: 'Աշխատանքը քո ողջ չափանիշը չէ։', f: ['low','overwhelmed'], c: ['work','self'] },
    { en: 'You can do good work without doing all of it today.', hy: 'Կարող ես լավ գործ անել՝ առանց այսօր ամբողջն անելու։', f: ['overwhelmed','anxious'], c: ['work'] },
    { en: "Someone else's urgency is not automatically yours.", hy: 'Ուրիշի շտապողականությունն ինքնաբերաբար քոնը չէ։', f: ['overwhelmed','angry'], c: ['work','people'] },
    { en: "You're allowed to stop at good enough.", hy: 'Դու իրավունք ունես կանգ առնել «բավական լավի» վրա։', f: ['overwhelmed','tired'], c: ['work','self'] },
    { en: "You wouldn't speak to anyone else the way you speak to yourself.", hy: 'Ուրիշի հետ այդպես չէիր խոսի, ինչպես խոսում ես քեզ հետ։', f: ['low','angry'], c: ['self'] },
    { en: "You can like yourself before you've fixed everything.", hy: 'Կարող ես հավանել քեզ՝ նախքան ամեն ինչ շտկելը։', f: ['low'], c: ['self'] },
    { en: 'The mistake was a thing you did, not a thing you are.', hy: 'Սխալը մի բան էր, որ արեցիր, ոչ թե այն, ինչ դու ես։', f: ['low','angry'], c: ['self','work'] },
    { en: 'Nothing has to be wrong for you to deserve a good day.', hy: 'Պարտադիր չէ ինչ-որ բան սխալ լինի, որ արժանի լինես լավ օրվա։', f: ['steady'], c: ['none','self'] },
    { en: "Steady is an achievement. It just doesn't announce itself.", hy: 'Կայունությունը ձեռքբերում է։ Պարզապես ինքն իրեն չի հայտարարում։', f: ['steady'], c: ['none','work'] },
    { en: 'You can enjoy this without waiting for it to end.', hy: 'Կարող ես վայելել սա՝ առանց սպասելու, որ ավարտվի։', f: ['steady'], c: ['none','people'] },
    { en: 'Ordinary days are most of a life. This one counts.', hy: 'Սովորական օրերը կյանքի մեծ մասն են։ Այս մեկը հաշվում է։', f: ['steady'], c: ['none'] },
    { en: 'Pick the next thing, not the whole list.', hy: 'Ընտրիր հաջորդ բանը, ոչ թե ողջ ցանկը։', f: ['overwhelmed'], c: ['work','none'] },
    { en: 'You can put something down without dropping it forever.', hy: 'Կարող ես մի բան վայր դնել՝ առանց ընդմիշտ թողնելու։', f: ['overwhelmed','tired'], c: ['work','people'] },
    { en: 'Sleep is not a reward for finishing.', hy: 'Քունը ավարտելու համար պարգև չէ։', f: ['tired'], c: ['health','work'] },
    { en: 'Money is a problem to solve, not proof of your worth.', hy: 'Փողը լուծելու խնդիր է, ոչ թե քո արժեքի ապացույց։', f: ['anxious','low','angry'], c: ['money','self'] },
    { en: 'You can be responsible about money without fearing it.', hy: 'Կարող ես պատասխանատու լինել փողի հարցում՝ առանց դրանից վախենալու։', f: ['anxious','steady'], c: ['money'] },
    { en: 'Feeling well today is worth noticing, not just using.', hy: 'Այսօր լավ զգալն արժե նկատել, ոչ միայն օգտագործել։', f: ['steady'], c: ['health','none'] },
    { en: 'A body that carried you this far deserves some kindness.', hy: 'Մարմինը, որ քեզ այսքան հեռու է բերել, բարության արժանի է։', f: ['steady','low'], c: ['health','self'] },
    { en: "The numbers will still be there after you've rested.", hy: 'Թվերը տեղում կլինեն նաև այն բանից հետո, երբ հանգստանաս։', f: ['overwhelmed','tired','anxious'], c: ['money','work'] },
    { en: 'You can only make the next decision, not all of them.', hy: 'Կարող ես կայացնել միայն հաջորդ որոշումը, ոչ բոլորը։', f: ['overwhelmed'], c: ['money','change','work'] },
    { en: "It's fair to be angry about something you can't control.", hy: 'Արդար է զայրանալ մի բանից, որը չես կարող վերահսկել։', f: ['angry'], c: ['change','money','health'] },
    { en: "Being let down doesn't mean you were foolish to hope.", hy: 'Հիասթափվելը չի նշանակում, որ հիմար էիր հուսալու համար։', f: ['angry','low'], c: ['people','change'] },
    { en: "You're allowed to feel fine without justifying it.", hy: 'Դու իրավունք ունես լավ զգալ՝ առանց արդարացնելու։', f: ['steady'], c: ['self','none'] },
    { en: "A good stretch isn't luck you'll be punished for.", hy: 'Լավ ժամանակահատվածը հաջողություն չէ, որի համար կպատժվես։', f: ['steady','anxious'], c: ['none','change'] }
  ]
};
